# Exercise 1: NumPy array and Indexing/Slicing

• 1.1) In this exercise, we will use the iris dataset. Load
the "iris.csv" using the appropriate method for this file
type (use the new functions from the package).

In [1]:
# Ensure ipykernel package is installed on our Python Environment "myenv"!
from si.io.csv_file import read_csv
from si.data.dataset import Dataset

iris = read_csv("../datasets/iris/iris.csv", features=True, label=True)
print("Shape:", iris.shape(), "\n")
print("Features:", iris.features, "\n")
print("Has Label?:", iris.has_label(), "\n")
print("Label/Classes:", iris.get_classes(), "\n")
print("Array:\n", iris.X)

Shape: (150, 4) 

Features: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object') 

Has Label?: True 

Label/Classes: ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica'] 

Array:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 

• 1.2) Select the penultimate independent variable.
What is the dimension of the resulting array?

In [2]:
from si.data.dataset import Dataset

penult_feature = iris.X[:, -2] # Select penultimate feature

# Must create a dataset out of the penultimate feature for our .shape() function (from Dataset class) to work
penult_feature_dataset = Dataset(X=penult_feature.reshape(-1, 1), y=None, features=[iris.features[-2]], label=None) # Note: The .reshape(-1, 1) function is used to maintain a 2D format

print("Penultimate independent variable:\n", penult_feature, "\n")
print("Shape of the resulting array:", penult_feature_dataset.shape())

Penultimate independent variable:
 [1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
 1.7 1.5 1.7 1.5 1.  1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
 1.3 1.5 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.
 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.
 4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.
 4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3
 5.8 6.1 5.1 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.
 4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9
 5.7 5.2 5.  5.2 5.4 5.1] 

Shape of the resulting array: (150, 1)


• 1.3) Select the last 10 samples from the iris dataset.
What is the mean of the last 10 samples for each
independent variable/feature?

In [3]:
from si.data.dataset import Dataset

last_10_samples_X = iris.X[-10:, :] # Select last 10 rows from the feature matrix
last_10_samples_y = iris.y[-10:]    # Select last 10 labels

# Must create a dataset out of just the last 10 samples for our get_mean() function (from Dataset class) to work
last_10_dataset = Dataset(X=last_10_samples_X, y=last_10_samples_y, features=iris.features, label=iris.label)

print("Mean of the last 10 samples for each independent variable:", last_10_dataset.get_mean())

Mean of the last 10 samples for each independent variable: [6.45 3.03 5.33 2.17]


• 1.4) Select all samples from the dataset with values
less than or equal to 6 for all independent
variables/features. How many samples do you obtain?

In [4]:
import numpy as np

condition = np.all(iris.X <= 6, axis=1)
filtered_samples = iris.X[condition]

print("Samples with values less than or equal to 6 in the dataset:", filtered_samples.shape[0])

Samples with values less than or equal to 6 in the dataset: 89


• 1.5) Select all samples with a class/label different
from 'Iris-setosa'. How many samples do you obtain?

In [5]:
condition = iris.y != "Iris-setosa"
filtered_samples = iris.X[condition]

print("Number of samples with a class/label different from 'Iris-setosa':", filtered_samples.shape[0])

Number of samples with a class/label different from 'Iris-setosa': 100


# Exercise 2: NumPy array Indexing/Slicing
Usage examples of dropna(), fillna() and remove_by_index(). 

Functions can be found in the Dataset class object, directory .\src\si\data\dataset.py.

### dropna() usage example

### fillna() usage example

### remove_by_index() usage example

# Exercise 3: Implementing SelectPercentile

3.3) Test the SelectPercentile class in a Jupyter notebook using the "iris.csv" dataset (classification).

In [6]:
import numpy as np
import os

from si.feature_selection.select_percentile import SelectPercentile
from si.io.csv_file import read_csv
from si.statistics.f_classification import f_classification

dataset = read_csv("../datasets/iris/iris.csv", features=True, label=True) # Defining the iris dataset as a variable 'dataset'

In [8]:
select_percentile = SelectPercentile(score_func=f_classification, percentile=50)    # Creates SelectPercentile instance with 50% of features selected based on f_classification
select_percentile.fit(iris)                                                         # Fit SelectPercentile to the iris dataset
transformed_dataset = select_percentile.transform(dataset)                          # Transform the dataset by selecting the best features according to the percentile

print(f"Features before SelectPercentile transformation: {dataset.features} \n")                      # Display features present in the iris dataset before being transformed by SelectPercentile

# Display the transformed features and data
print(f"Selected features after SelectPercentile transformation: {transformed_dataset.features} \n")
print(f"First five rows of the transformed data:\n{transformed_dataset.X[:5]} \n")
print(f"Number of features before transformation: {len(iris.features)}")
print(f"Number of features after transformation: {len(transformed_dataset.features)}")

Features before SelectPercentile: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object') 

Selected features after SelectPercentile transformation: ['petal_width', 'petal_length'] 

First five rows of the transformed data:
[[0.2 1.4]
 [0.2 1.4]
 [0.2 1.3]
 [0.2 1.5]
 [0.2 1.4]] 

Number of features before transformation: 4
Number of features after transformation: 2
